use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail, ensure};
use celsius::analytic_sky::{AnalyticSky, prepare};
use celsius::astro::{moon_state, sun_position, to_sky_fracs};
use celsius::colorspace::{oklab_to_rgb, rgb_u8_to_oklab};
use celsius::scene::{Chrome, SkyState, Sun};
use celsius::{Gradient, load_scene, render};
use chrono::{DateTime, NaiveDateTime};
use font8x8::{BASIC_FONTS, UnicodeFonts};
use image::imageops::{FilterType, overlay, resize};
use image::{ImageFormat, ImageReader, Rgb, RgbImage};

const CONTACT_GAP: u32 = 16;
const CONTACT_PADDING: u32 = 16;
const CONTACT_LABEL_HEIGHT: u32 = 24;
pub const SKY_WIDTH: u32 = 104;
pub const SKY_HEIGHT: u32 = 50;

#[derive(Clone, Debug)]
pub struct SceneSpec<'a> {
    pub name: &'a str,
    pub lat: f64,
    pub lon: f64,
    pub unix_utc: i64,
    pub at_label: &'a str,
    pub facing: f64,
    pub turbidity: f64,
    pub stops: usize,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct DiffMetrics {
    pub differing: usize,
    pub total: usize,
    pub mean_rgb_distance: f64,
    pub max_rgb_distance: f64,
    pub mean_delta_e: f64,
    pub max_delta_e: f64,
    pub p95_delta_e: f64,
}

pub fn parse_at(value: &str) -> Result<i64> {
    if let Ok(parsed) = DateTime::parse_from_rfc3339(value) {
        return Ok(parsed.timestamp());
    }
    for format in ["%Y-%m-%dT%H:%M%:z", "%Y-%m-%dT%H:%M:%S%:z"] {
        if let Ok(parsed) = DateTime::parse_from_str(value, format) {
            return Ok(parsed.timestamp());
        }
    }
    if let Some(utc) = value.strip_suffix('Z') {
        for format in ["%Y-%m-%dT%H:%M", "%Y-%m-%dT%H:%M:%S"] {
            if let Ok(parsed) = NaiveDateTime::parse_from_str(utc, format) {
                return Ok(parsed.and_utc().timestamp());
            }
        }
    }
    for format in ["%Y-%m-%dT%H:%M", "%Y-%m-%dT%H:%M:%S"] {
        if let Ok(parsed) = NaiveDateTime::parse_from_str(value, format) {
            return Ok(parsed.and_utc().timestamp());
        }
    }
    bail!("invalid time {value:?}; use RFC3339 or YYYY-MM-DDTHH:MM")
}

pub fn scene_toml(spec: &SceneSpec<'_>) -> Result<String> {
    ensure!(!spec.name.is_empty(), "scene name cannot be empty");
    ensure!(
        spec.name
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_' || byte == b'-'),
        "scene name may contain only ASCII letters, numbers, hyphens, and underscores"
    );
    ensure!(spec.stops >= 2, "a scene needs at least two gradient stops");
    ensure!(
        spec.turbidity.is_finite() && spec.turbidity > 0.0,
        "turbidity must be positive"
    );

    let sun = sun_position(spec.lat, spec.lon, spec.unix_utc);
    let moon = moon_state(spec.lat, spec.lon, spec.unix_utc);
    let (sun_x, sun_y) = to_sky_fracs(&sun, spec.facing);
    let (moon_x, moon_y) = to_sky_fracs(&moon.altaz, spec.facing);
    let fallback = celsius::weather::clear_sky_gradient(sun.altitude);
    let analytic = (sun.altitude > 0.0).then(|| {
        prepare(&AnalyticSky {
            sun_alt: sun.altitude,
            sun_az: sun.azimuth,
            center_az: spec.facing,
            turbidity: spec.turbidity,
            blend: 1.0,
        })
    });

    let mut lines = vec![
        format!("# {}", spec.name),
        format!(
            "# {:.4}, {:.4} at {} | sun alt {:.1} deg, az {:.1} deg | turbidity {:.1}",
            spec.lat, spec.lon, spec.at_label, sun.altitude, sun.azimuth, spec.turbidity
        ),
        format!(
            "# Meteorological intent: clear-sky baseline at turbidity {:.1}; replace this when tuning a specific phenomenon.",
            spec.turbidity
        ),
        "# Expected failure mode: this scaffold reads generic until its gradient and effects are tuned against observed conditions.".to_string(),
        "# Generated by `just lab-new`; tune the scene by hand after rendering it.".to_string(),
        String::new(),
        "[gradient]".to_string(),
        "stops = [".to_string(),
    ];
    for index in 0..spec.stops {
        let t = index as f64 / (spec.stops - 1) as f64;
        let color = analytic
            .as_ref()
            .map_or_else(|| fallback.sample(t), |sky| sky.sample(0.5, t));
        let rgb = oklab_to_rgb(color);
        lines.push(format!(
            "  {{ t = {t:.2}, rgb = [{}, {}, {}] }},",
            rgb.r, rgb.g, rgb.b
        ));
    }
    lines.extend([
        "]".to_string(),
        String::new(),
        "[sun]".to_string(),
        format!("x_frac = {sun_x:.3}"),
        format!("y_frac = {sun_y:.3}"),
        "radius = 3.5".to_string(),
        format!("visible = {}", sun.altitude > -0.5),
    ]);
    if moon.altaz.altitude > 0.0 {
        lines.extend([
            String::new(),
            "[moon]".to_string(),
            format!("x_frac = {moon_x:.3}"),
            format!("y_frac = {moon_y:.3}"),
            "radius = 6.5".to_string(),
            format!("phase = {:.3}", moon.phase),
            "visible = true".to_string(),
        ]);
    }
    lines.extend([
        String::new(),
        "[chrome]".to_string(),
        "header_left = \"celsius\"".to_string(),
        format!(
            "header_right = \"{:.2},{:.2}   {}\"",
            spec.lat, spec.lon, spec.at_label
        ),
        "footer = \"edit me   conditions   wind --\"".to_string(),
        "keys = \"<- -> scrub   tab day   t now   l location   ? help   q quit\"".to_string(),
        String::new(),
    ]);
    Ok(lines.join("\n"))
}

pub fn compare_images(
    rendered: &RgbImage,
    reference: &RgbImage,
) -> Result<(DiffMetrics, RgbImage)> {
    ensure!(
        rendered.dimensions() == reference.dimensions(),
        "image dimensions differ: rendered {:?}, reference {:?}",
        rendered.dimensions(),
        reference.dimensions()
    );
    ensure!(!rendered.is_empty(), "images cannot be empty");

    let mut differing = 0usize;
    let mut rgb_distances = Vec::with_capacity(rendered.len() / 3);
    let mut distances = Vec::with_capacity(rendered.len() / 3);
    let mut heatmap = RgbImage::new(rendered.width(), rendered.height());
    for (index, (actual, expected)) in rendered.pixels().zip(reference.pixels()).enumerate() {
        differing += usize::from(actual != expected);
        let red = f64::from(actual[0]) - f64::from(expected[0]);
        let green = f64::from(actual[1]) - f64::from(expected[1]);
        let blue = f64::from(actual[2]) - f64::from(expected[2]);
        rgb_distances.push(((red * red + green * green + blue * blue) / 3.0).sqrt());
        let a = rgb_u8_to_oklab(actual[0], actual[1], actual[2]);
        let b = rgb_u8_to_oklab(expected[0], expected[1], expected[2]);
        let delta = ((a.l - b.l).powi(2) + (a.a - b.a).powi(2) + (a.b - b.b).powi(2)).sqrt();
        distances.push(delta);
        let intensity = (delta * 510.0).round().clamp(0.0, 255.0) as u8;
        let color = if intensity < 128 {
            Rgb([intensity.saturating_mul(2), 0, 0])
        } else {
            Rgb([255, intensity.saturating_sub(128).saturating_mul(2), 0])
        };
        let x = index as u32 % rendered.width();
        let y = index as u32 / rendered.width();
        heatmap.put_pixel(x, y, color);
    }

    distances.sort_by(f64::total_cmp);
    let total = distances.len();
    let mean_rgb_distance = rgb_distances.iter().sum::<f64>() / total as f64;
    let max_rgb_distance = rgb_distances.into_iter().fold(0.0, f64::max);
    let mean_delta_e = distances.iter().sum::<f64>() / total as f64;
    let max_delta_e = *distances.last().context("image distance list is empty")?;
    let p95_index = ((total as f64 * 0.95).ceil() as usize).saturating_sub(1);
    let metrics = DiffMetrics {
        differing,
        total,
        mean_rgb_distance,
        max_rgb_distance,
        mean_delta_e,
        max_delta_e,
        p95_delta_e: distances[p95_index],
    };
    Ok((metrics, heatmap))
}

pub fn contact_dimensions(
    scene_count: usize,
    columns: usize,
    tile_width: u32,
    tile_height: u32,
) -> (u32, u32) {
    if scene_count == 0 || columns == 0 {
        return (0, 0);
    }
    let columns = columns.min(scene_count);
    let rows = scene_count.div_ceil(columns);
    let width = CONTACT_PADDING * 2
        + tile_width * columns as u32
        + CONTACT_GAP * columns.saturating_sub(1) as u32;
    let cell_height = CONTACT_LABEL_HEIGHT + tile_height;
    let height = CONTACT_PADDING * 2
        + cell_height * rows as u32
        + CONTACT_GAP * rows.saturating_sub(1) as u32;
    (width, height)
}

pub fn repo_root() -> Result<PathBuf> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .context("celsius-lab must live at tools/celsius-lab")
}

pub fn scene_path(root: &Path, name_or_path: &str) -> PathBuf {
    let supplied = Path::new(name_or_path);
    if supplied.is_file() {
        supplied.to_path_buf()
    } else {
        let name = name_or_path.strip_suffix(".toml").unwrap_or(name_or_path);
        root.join("scenes").join(format!("{name}.toml"))
    }
}

pub fn render_scene(path: &Path) -> Result<RgbImage> {
    let scene = load_scene(path).with_context(|| format!("loading {}", path.display()))?;
    render_state(&scene, SKY_WIDTH, SKY_HEIGHT)
}

pub fn render_state(state: &SkyState, width: u32, height: u32) -> Result<RgbImage> {
    let pixels = render(state, width, height);
    to_rgb(pixels)
}

/// Render a state and then apply the tick overlays at `t` seconds, the way the TUI composites a frame. `render()` alone can never show a meteor or a flash: both live outside the pixel pipeline and are driven by the app clock, so a still PNG of a thunderstorm is always between strikes. This is the only way to see them without a terminal.
pub fn render_state_at(state: &SkyState, width: u32, height: u32, t: f64) -> Result<RgbImage> {
    let mut pixels = render(state, width, height);
    if let Some(lightning) = state.lightning.as_ref() {
        celsius::lightning::overlay(&mut pixels, lightning, t);
    }
    if let Some(meteors) = state.meteors.as_ref() {
        celsius::meteors::overlay(&mut pixels, meteors, t);
    }
    to_rgb(pixels)
}

fn to_rgb(pixels: celsius::PixelBuffer) -> Result<RgbImage> {
    let png = celsius::terminal::encode_png(&pixels).context("encoding production PNG")?;
    Ok(image::load_from_memory_with_format(&png, ImageFormat::Png)
        .context("decoding production PNG")?
        .to_rgb8())
}

/// A dark, clear night with one shower's meteors attached, for previewing radiant geometry off-season. The backdrop is the locked `moonless_darksky` scene so the stars and gradient are production values, and `Meteors::new` is the same constructor the live forecast path calls.
pub fn meteor_state(
    root: &Path,
    name: &str,
    unix_utc: i64,
    lat: f64,
    lon: f64,
    facing: f64,
    duration_s: f64,
) -> Result<SkyState> {
    let backdrop = root.join("scenes/moonless_darksky.toml");
    let mut state =
        load_scene(&backdrop).with_context(|| format!("loading {}", backdrop.display()))?;
    state.name = name.to_string();
    state.unix_utc = unix_utc;
    state.meteors = Some(celsius::meteors::Meteors::new(
        mix_preview_seed(unix_utc, lat, lon),
        unix_utc,
        lat,
        lon,
        facing,
        duration_s,
        (SKY_WIDTH, SKY_HEIGHT),
    ));
    Ok(state)
}

/// Every meteor of the run composited onto one frame, each at its own moment of peak brightness. Physically this is a long exposure, not an instant: a single frame of a ZHR-100 shower usually holds zero meteors, so a still preview of the real thing shows an empty sky. Replaying every peak is what makes the radiant legible, because the streaks all point away from one spot.
pub fn render_meteor_map(state: &SkyState, width: u32, height: u32) -> Result<(RgbImage, usize)> {
    let mut pixels = render(state, width, height);
    let Some(meteors) = state.meteors.as_ref() else {
        return Ok((to_rgb(pixels)?, 0));
    };
    for m in &meteors.meteors {
        celsius::meteors::overlay(&mut pixels, meteors, m.t_start + m.life * 0.5);
    }
    Ok((to_rgb(pixels)?, meteors.meteors.len()))
}

/// A stable seed for previews. The live path seeds from (place, day) so a sky is reproducible; a preview only needs the same instant to give the same meteors twice.
fn mix_preview_seed(unix_utc: i64, lat: f64, lon: f64) -> u32 {
    let day = unix_utc.div_euclid(86_400) as u32;
    let place = ((lat * 1000.0) as i32 as u32) ^ ((lon * 1000.0) as i32 as u32).rotate_left(16);
    day ^ place.rotate_left(8)
}

/// A bare analytic sky at one sun elevation and turbidity, for sweeping the Preetham model without a forecast. The gradient is black on purpose: every visible colour then provably comes from the analytic model rather than a palette underneath it.
pub fn analytic_state(sun_alt: f64, turbidity: f64) -> SkyState {
    let center_az = 180.0;
    SkyState {
        name: format!("alt{}_t{}", sun_alt as i32, turbidity as i32),
        gradient: Gradient::from_rgb_stops(&[(0.0, [0, 0, 0]), (1.0, [0, 0, 0])]),
        sun: Sun {
            x_frac: 0.5,
            y_frac: (1.0 - sun_alt.to_radians().sin()).clamp(0.0, 1.0),
            radius: 4.0,
            visible: sun_alt > 0.0,
        },
        clouds: Vec::new(),
        chrome: Chrome {
            header_left: String::new(),
            header_right: String::new(),
            footer: String::new(),
            keys: String::new(),
            status: String::new(),
            footer_tiers: Vec::new(),
            keys_tiers: Vec::new(),
        },
        haze: None,
        stars: None,
        moon: None,
        precipitation: None,
        lightning: None,
        meteors: None,
        horizon_glow: None,
        analytic: Some(AnalyticSky {
            sun_alt,
            sun_az: center_az,
            center_az,
            turbidity,
            blend: 1.0,
        }),
        wind_speed_kmh: 0.0,
        unix_utc: 0,
    }
}

pub fn load_reference(path: &Path) -> Result<RgbImage> {
    let image = ImageReader::open(path)
        .with_context(|| format!("opening {}", path.display()))?
        .decode()
        .with_context(|| format!("decoding {}", path.display()))?
        .to_rgb8();
    Ok(resize(&image, SKY_WIDTH, SKY_HEIGHT, FilterType::Lanczos3))
}

pub fn save_scaled(image: &RgbImage, path: &Path, scale: u32) -> Result<()> {
    ensure!(scale > 0, "scale must be at least 1");
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    let scaled = resize(
        image,
        image.width() * scale,
        image.height() * scale,
        FilterType::Nearest,
    );
    scaled
        .save(path)
        .with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

pub fn contact_sheet(
    scenes: &[(String, RgbImage)],
    columns: usize,
    scale: u32,
) -> Result<RgbImage> {
    ensure!(!scenes.is_empty(), "no scenes found");
    ensure!(columns > 0, "columns must be at least 1");
    ensure!(scale > 0, "scale must be at least 1");
    let tile_width = SKY_WIDTH * scale;
    let tile_height = SKY_HEIGHT * scale;
    let (width, height) = contact_dimensions(scenes.len(), columns, tile_width, tile_height);
    let mut sheet = RgbImage::from_pixel(width, height, Rgb([8, 12, 20]));
    for (index, (name, image)) in scenes.iter().enumerate() {
        let column = index % columns;
        let row = index / columns;
        let x = CONTACT_PADDING + column as u32 * (tile_width + CONTACT_GAP);
        let y = CONTACT_PADDING + row as u32 * (tile_height + CONTACT_LABEL_HEIGHT + CONTACT_GAP);
        draw_text(&mut sheet, name, x, y + 7, 1, Rgb([214, 222, 236]));
        let tile = resize(image, tile_width, tile_height, FilterType::Nearest);
        overlay(
            &mut sheet,
            &tile,
            i64::from(x),
            i64::from(y + CONTACT_LABEL_HEIGHT),
        );
    }
    Ok(sheet)
}

fn draw_text(image: &mut RgbImage, text: &str, x: u32, y: u32, scale: u32, color: Rgb<u8>) {
    let mut cursor = x;
    for character in text.chars() {
        let Some(glyph) = BASIC_FONTS.get(character) else {
            cursor += 9 * scale;
            continue;
        };
        for (row, bits) in glyph.iter().enumerate() {
            for column in 0..8 {
                if bits & (1 << column) == 0 {
                    continue;
                }
                for dy in 0..scale {
                    for dx in 0..scale {
                        let px = cursor + column * scale + dx;
                        let py = y + row as u32 * scale + dy;
                        if px < image.width() && py < image.height() {
                            image.put_pixel(px, py, color);
                        }
                    }
                }
            }
        }
        cursor += 9 * scale;
    }
}

#[cfg(test)]
mod tests {
    use image::{Rgb, RgbImage};

    use super::*;

    #[test]
    fn parse_at_treats_naive_datetime_as_utc() {
        let parsed = parse_at("2026-04-11T06:14").unwrap();

        assert_eq!(parsed, 1_775_888_040);
    }

    #[test]
    fn compare_images_reports_zero_for_identical_pixels() {
        let image = RgbImage::from_pixel(2, 2, Rgb([34, 82, 162]));

        let (metrics, _) = compare_images(&image, &image).unwrap();

        assert_eq!(metrics.mean_rgb_distance, 0.0);
        assert_eq!(metrics.mean_delta_e, 0.0);
    }

    #[test]
    fn compare_images_marks_identical_pixels_black() {
        let image = RgbImage::from_pixel(1, 1, Rgb([34, 82, 162]));

        let (_, heatmap) = compare_images(&image, &image).unwrap();

        assert_eq!(*heatmap.get_pixel(0, 0), Rgb([0, 0, 0]));
    }

    #[test]
    fn compare_images_reports_rgb_channel_distance() {
        let rendered = RgbImage::from_pixel(1, 1, Rgb([255, 0, 0]));
        let reference = RgbImage::from_pixel(1, 1, Rgb([0, 0, 0]));

        let (metrics, _) = compare_images(&rendered, &reference).unwrap();

        let expected = 255.0 / 3.0_f64.sqrt();
        assert!((metrics.mean_rgb_distance - expected).abs() < f64::EPSILON);
        assert!((metrics.max_rgb_distance - expected).abs() < f64::EPSILON);
    }

    #[test]
    fn contact_dimensions_fit_every_scene() {
        let (width, height) = contact_dimensions(11, 3, 312, 150);

        assert_eq!((width, height), (1_000, 776));
    }

    #[test]
    fn scene_toml_loads_with_the_production_parser() {
        let spec = SceneSpec {
            name: "test_dawn",
            lat: 53.5511,
            lon: 9.9937,
            unix_utc: 1_765_000_000,
            at_label: "2025-12-06T05:46Z",
            facing: 180.0,
            turbidity: 3.0,
            stops: 7,
        };
        let text = scene_toml(&spec).unwrap();
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test_dawn.toml");
        std::fs::write(&path, text).unwrap();

        let scene = celsius::load_scene(path).unwrap();

        assert_eq!(scene.name, "test_dawn");
    }
}
